pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3004:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Tests') {
            steps {
                sh './jenkins/scripts/test.sh'  // Replace with your unit test command
            }
            
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
    post {
        failure {
            // Notify team on test failure
            emailext (
                subject: "Unit Tests Failed",
                body: "The unit tests have failed. Please investigate.",
                to: "sanjaych0311@gmail.com"  // Replace with the correct email address
            )
        }
    }
}

